ValueSet: CZ_eHDSIVaccineAtcVS
Id: cz-ehdsi-vaccine-atc-vs
Title: "EU Vaccine"
Description: "Czech vaccine type value set. This value set includes all ATC codes from EU eHDSIVaccine value set."
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2022-11-23T16:13:20-01:00"
* ^publisher = "Národní centrum elektronického zdravotnictví"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "http://www.ncez.macr.cz"
* ^jurisdiction = $m49.htm#CZE
* ^immutable = false

* $atc#J07AE01 "cholera, inaktivovaná celobuněčná vakcína"
* $atc#J07AG01 "haemophilus influenzae B, purifikovaný antigen konjugovaný"
* $atc#J07AH "Vakcíny proti meningokokovým infekcím"
* $atc#J07AH05 "jiná meningokokoková polyvalentní vakcína, purifikované polysacharidové antigeny"
* $atc#J07AH10 "meningococcus A, purifikovaný polysacharidový antigen konjugovaný"
* $atc#J07AJ01 "pertuse, inaktivovaná celobuněčná vakcína"
* $atc#J07BA "Vakcína proti virové encefalitidě"
* $atc#J07BD52 "spalničky-příušnice-zarděnky, živá atenuovaná vakcína"
* $atc#J07BD54 "spalničky-příušnice-zarděnky-plané neštovice, živá atenuovaná vakcína"
* $atc#J07BF "Vakcíny proti poliomyelitidě"
* $atc#J07BG "Vakcíny proti vzteklině"
* $atc#J07BH02 "rotavirus, pentavalentní vakcína, živý, přetříděný virus"
* $atc#J07AC01 "antigen anthraxu"
* $atc#J07AM51 "tetanový toxoid, kombinace s difterickým toxoidem"
* $atc#J07AP03 "břišní tyfus, purifikovaný polysacharidový antigen"
* $atc#J07AP10 "břišní tyfus, kombinace s paratyfem"
* $atc#J07BB02 "chřipka, inaktivovaná vakcína, štěpený virus nebo povrchový antigen"
* $atc#J07BB03 "chřipka, živý atenuovaný virus"
* $atc#J07BC20 "kombinace vakcín proti hepatitidě"
* $atc#J07BD "Vakcíny proti spalničkám"
* $atc#J07BG01 "vzteklina, inaktivovaný celý virus"
* $atc#J07BJ "Vakcíny proti zarděnkám"
* $atc#J07BK02 "zoster, živý atenuovaný virus"
* $atc#J07BX "Jiné virové vakcíny"
* $atc#J07AD01 "brucelový antigen"
* $atc#J07AF "Vakcíny proti difterii"
* $atc#J07AH03 "meningococcus A,C, bivakcína, purifikované polysacharidové antigeny"
* $atc#J07AH04 "meningococcus A,C,Y,W-135, tetravakcína, purifikované polysacharidové antigeny"
* $atc#J07AJ52 "pertuse, purifikovaný antigen, kombinace s toxoidy"
* $atc#J07BE "Vakcíny proti příušnicím"
* $atc#J07BF03 "poliomyelitida, trivalentní vakcína, inaktivovaný celý virus"
* $atc#J07BF04 "poliomyelitida, perorální bivalentní vakcína, živý atenuovaný virus"
* $atc#J07BM01 "papilomavirus lidský (typ 6, 11, 16, 18)"
* $atc#J07BM03 "protein lidského papillomaviru typu 6, 11, 16, 18, 31, 33, 45, 52, 58)"
* $atc#J07CA02 "difterie-pertuse-poliomyelitida-tetanus"
* $atc#J07CA03 "difterie-rubeola-tetanus"
* $atc#J07CA04 "haemophilus influenzae B-poliomyelitida"
* $atc#J07CA06 "difterie-haemophilus influenzae B-pertuse-poliomyelitida-tetanus"
* $atc#J07CA07 "difterie-hepatitida B-tetanus"
* $atc#J07CA08 "haemophilus influenzae B-hepatitida B"
* $atc#J07CA10 "břišní tyfus-hepatitida A"
* $atc#J07CA13 "difterie-haemophulus influenzae B-pertuse-tetanus-hepatitida B-meningococcus A+C"
* $atc#J07AE "Vakcíny proti choleře"
* $atc#J07AE51 "cholera, kombinace s břišním tyfem, inaktivovaná celobuněčná vakcína"
* $atc#J07AF01 "difterický toxoid"
* $atc#J07AG51 "haemophilus influenzae B, kombinace s toxoidy"
* $atc#J07AG53 "haemophilus influenzae B, meningococcus C, konjugovaná vakcína"
* $atc#J07AH01 "meningococcus A, purifikovaný polysacharidový antigen"
* $atc#J07AH06 "meningococcus B, OMV vakcína"
* $atc#J07AH09 "meningococcus B, multikomponentní vakcína"
* $atc#J07AN "Vakcíny proti tuberkulóze"
* $atc#J07AR "Vakcíny proti skvrnitému tyfu"
* $atc#J07BA01 "klíšťová encefalitida, inaktivovaný celý virus"
* $atc#J07BB01 "chřipka, inaktivovaný celý virus"
* $atc#J07BC01 "hepatitida B, purifikovaný antigen"
* $atc#J07BD51 "spalničky, kombinace s příušnicemi, živá atenuovaná vakcína"
* $atc#J07BF02 "poliomyelitida, perorální trivalentní vakcína, živý atenuovaný virus"
* $atc#J07BK "Vakcíny proti infekcím vyvolaným virem varicella-zoster"
* $atc#J07BK03 "zoster, purifikovaný antigen"
* $atc#J07BX03 "vakcíny proti covid-19"
* $atc#J07BX04 "vakcíny proti infekcím vyvolaným virem dengue"
* $atc#J07CA "Bakteriální a virové vakcíny, kombinované"
* $atc#J07CA12 "difterie-pertuse-poliomyelitida-tetanus-hepatitida B"
* $atc#J07AD "Vakcíny proti brucelóze"
* $atc#J07AG54 "haemophilus influenzae B, meningococcus C, Y, konjugovaná vakcína"
* $atc#J07AH07 "meningococcus C, purifikovaný polysacharidový antigen konjugovaný"
* $atc#J07AJ02 "pertuse, purifikovaný antigen"
* $atc#J07AK "Vakcíny proti moru"
* $atc#J07AM52 "tetanový toxoid, kombinace s imunoglobulinem proti tetanu"
* $atc#J07AP "Vakcíny proti břišnímu tyfu"
* $atc#J07AP01 "břišní tyfus, perorální živá atenuovaná vakcína"
* $atc#J07AR01 "skvrnitý tyfus, inaktivovaná celobuněčná vakcína"
* $atc#J07BA03 "japonská encefalitida, živý atenuovaný virus"
* $atc#J07BC "Vakcíny proti hepatitidě"
* $atc#J07BC02 "hepatitida A, inaktivovaný celý virus"
* $atc#J07BE01 "příušnice, živý atenuovaný virus"
* $atc#J07BF01 "poliomyelitida, perorální monovalentní vakcína, živý atenuovaný virus"
* $atc#J07BH01 "rotavirus, živý atenuovaný virus"
* $atc#J07BJ01 "zarděnky, živý atenuovaný virus"
* $atc#J07BK01 "plané neštovice, živý atenuovaný virus"
* $atc#J07BL "Vakcína proti žluté zimnici"
* $atc#J07BL01 "žlutá zimnice, živý atenuovaný virus"
* $atc#J07CA09 "difterie-haemophilus influenzae B-pertuse-poliomyelida-tetanus-hepatitida B"
* $atc#J07CA11 "difterie-haemophilus influenzae B-pertuse-tetanus-hepatitida B"
* $atc#J07AE02 "cholera, živá atenuovaná vakcína"
* $atc#J07AG "Vakcíny proti infekcím vyvolaným haemophilus influenzae typu B"
* $atc#J07AG52 "haemophilus influenzae B, kombinace s pertusí a toxoidy"
* $atc#J07AP02 "břišní tyfus, inaktivovaná celobuněčná vakcína"
* $atc#J07BB04 "chřipka, viru podobné částice"
* $atc#J07BD01 "spalničky, živý atenuovaný virus"
* $atc#J07BH "Vakcíny proti rotavirovým průjmovým infekcím"
* $atc#J07BX01 "vakcíny proti pravým neštovicím"
* $atc#J07AJ "Vakcíny proti pertusi"
* $atc#J07AJ51 "pertuse, inaktivovaná celobuněčná vakcína, kombinace s toxoidy"
* $atc#J07AL "Vakcíny proti pneumokokovým infekcím"
* $atc#J07AL01 "pneumococcus, purifikované polysacharidové antigeny"
* $atc#J07AL02 "pneumococcus, purifikované polysacharidové antigeny konjugované"
* $atc#J07AM "Vakcíny proti tetanu"
* $atc#J07AM01 "tetanový toxoid"
* $atc#J07AX "Jiné bakteriální vakcíny"
* $atc#J07BA02 "japonská encefalitida, inaktivovaný celý virus"
* $atc#J07BB "Vakcíny proti chřipce"
* $atc#J07BD53 "spalničky, kombinace se zarděnkami, živá atenuovaná vakcína"
* $atc#J07BM "Vakcíny proti papilomaviru"
* $atc#J07CA01 "difterie-poliomyelitida-tetanus"
* $atc#J07CA05 "difterie-hepatitida B-pertuse-tetanus"
* $atc#J07AC "Vakcíny proti antraxu"
* $atc#J07AH02 "jiná meningokoková monovalentní vakcína, purifikovaný polysacharidový antigen"
* $atc#J07AH08 "meningococcus A,C,Y,W-135, tetravakcína, purifikované polysacharidové antigeny konjugované"
* $atc#J07AK01 "mor, inaktivovaná celobuněčná vakcína"
* $atc#J07AL52 "pneumococcus, purifikované polysacharidové antigeny a haemophilus influenzae, konjugovaná vakcína"
* $atc#J07AN01 "tuberkulóza, živá atenuovaná vakcína"
* $atc#J07BJ51 "zarděnky, kombinace s příušnicemi, živá atenuovaná vakcína"
* $atc#J07BM02 "papilomavirus lidský (typ 16, 18)"
* $atc#J07BX02 "vakcíny proti ebole"